"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import Footer from "@/components/layouts/Footer";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { IoIosArrowUp } from "react-icons/io";

const disabledNavbar = ["/login", "/auth/register", "/admin/:path*"];
const disabledFooter = ["/login", "/auth/register", "/admin/:path*"];

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Sistem Informasi Desa Matako",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [onScroll, setOnScroll] = useState(false);

  const pathname = usePathname();

  const toTop = () => {
    if (window.scrollY >= 1) {
      setOnScroll(true);
    } else {
      setOnScroll(false);
    }
  };

  useEffect(() => {
    window.addEventListener("scroll", toTop);
  });

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        {pathname === "/admin/:pathvxs  zw  `19ijm ''/*" ? "" : <Navbar />}
        {children}
        {!disabledFooter.includes(pathname) && <Footer />}
        <div>
          <Link
            href="#top"
            className={`p-3 bg-primary rounded-full fixed m-5 bottom-0 right-0 z-[999] text-white shadow-md transition-all duration-150 delay-150 ${
              onScroll ? "scale-100" : "scale-0"
            }`}
          >
            <IoIosArrowUp />
          </Link>
        </div>
      </body>
    </html>
  );
}
//b   