import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import Navbar from "./navbar";
// import Footer from "@/components/layouts/Footer";


const disabledNavbar = ["/login", "/auth/register", "/admin/:path*"];
const disabledFooter = ["/login", "/auth/register", "/admin/:path*"];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sistem Informasi Desa Matako",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        {/* {pathname === "/admin/:pathvxs  zw  `19ijm ''/*" ? "" : <Navbar />} */}
        {children}
        {/* {!disabledFooter.includes(pathname) && <Footer />} */}
      </body>
    </html>
  );
}
//b
